### ISSUE TITLE
RichTextFX comment highlight, but how?

### ISSUE THREAD

**Issue by mathiasene** [TomasMikula/RichTextFX#133]
Hello, I'm new to use RichTextFX and I'll like to know how to do it possible to highlight comments. I use the code from JavaKeywords.java.

How can I add support for highlightning comments that start with "//" or "/*" or ";". It'll be really nice to know how to do that. I'm totally blank there.

**Comment by TomasMikula** [comment]
JavaKeywords demo uses _regular expressions_ to parse the code. Are you familiar with regular expressions? If you want to extend JavaKeywords with comments, you need to define a regular expression that matches a comment. In the demo, there are already several regular expressions defined for such things as keywords, string literals and different types of parentheses.

Regular expressions are just one way to do the parsing. It is used in the demo, because it's fairly simple, but you can use whatever parser you want to parse your code. What CodeArea cares about are style ranges that you get out of your parser. In the demo, style ranges are computed by the `computeHighlighting` method.

**Comment by TomasMikula** [comment]
Here is how I added highlighting of Java comments to the demo: b51c205bcdd096a03e826307aaf3b6cd2ae0a4aa. It is really just three lines of code added (not counting the change in the sample code to include some comments).

**Comment by mathiasene** [comment]
Thanks.  I'll work on it :).
