### ISSUE TITLE
Lines appearing after coping and refilling text

### ISSUE THREAD

**Issue by spoeck** [TomasMikula/RichTextFX#141]
Step 1:
I copy the text out of Java Keywords Demo and filling it into Notepad++. Everything perfect.

Step 2:
After that, I copy the text out of the Notepad++ and filling it into Java Keywords Demo. Everything perfect.

Step 3:
I repeat Step 1 and have the effect that between every code line is a empty line appearing.

**Comment by bigDevDe** [comment]
Hi Tomas,

I have the same problem! There are double line breaks after several copy and paste from/into the TextArea (in the TextArea these double linebreaks are not displayed, only outside in a text editor)

Regards Michael

**Comment by bigDevDe** [comment]
It seems like when you paste text into the area, then the line breaks are doubled...

**Comment by TomasMikula** [comment]
This seems like a Windows-only problem. Or can anyone reproduce it on Mac or Linux? I only have Mac and Linux available.

The cause is likely the following two "features" not working well together:
1. RichTextFX preserves whatever line terminator characters the file has. This means that if you `insertText` into the text area and then `getText`, you get the same String (no conversion of line terminators happens). This means, for example, that if you open a file with Unix line terminators (`\n`) on Windows and save it back, it will be saved with Unix line terminators.
2. JavaFX clipboard seems to be converting `\n` to system-specific line terminators on copy and system-specific line terminators to `\n` on paste.

As a result, if you copy text with Windows line terminators (`\r\n`) on Windows, JavaFX clipboard converts `\n` to `\r\n`, resulting in `\r\r\n`. If you paste it right back, JavaFX clipboard undoes this, RichTextFX receives `\r\n` and recognizes it as a single Windows line terminator. If, however, you paste it to a non-Java program, the program receives `\r\r\n` and treats that as two line terminators (`\r` and `\r\n`).

**Comment by JordanMartinez** [comment]
I downloaded the JavaKeywords demo and tested it on Linux. After doing the above method using Linux's GEdit (Text Editor) and again using a Word Processor (Kingsoft Writer), I didn't have the problem.

**Comment by TomasMikula** [comment]
Thanks for testing, Jordan!

**Comment by bigDevDe** [comment]
Hi Tomas,

thanks for your reply. I really get double 0D0A0D0A (\r\n\r\n). Do you suggest a workaround?

**Comment by TomasMikula** [comment]
The workaround would be to override <kbd>Ctrl</kbd>+<kbd>C</kbd>, <kbd>Ctrl</kbd>+<kbd>X</kbd>, <kbd>Ctrl</kbd>+<kbd>V</kbd> and do the right thing there. You would put the selected text to the clipboard, with all line terminators replaced by `\n`. This would be even easier to change in RichTextFX directly. However, it would mean that <kbd>Ctrl</kbd>+<kbd>C</kbd> immediately followed by <kbd>Ctrl</kbd>+<kbd>V</kbd> within RichTextFX could change the line terminators in the copy-pasted text, which I'm not sure is desired.

**Comment by bigDevDe** [comment]
Thank you for your reply, Tomas!

**Comment by hbrackmann** [comment]
another possible workaround using awt
```java
codeArea.addEventFilter(KeyEvent.KEY_RELEASED, new EventHandler<KeyEvent>() {
            @Override
            public void handle(KeyEvent event) {
                if (event.isControlDown() && event.getCode() == KeyCode.C){
                    java.awt.datatransfer.Clipboard clipboard = java.awt.Toolkit.getDefaultToolkit().getSystemClipboard();
                    java.awt.datatransfer.StringSelection stringSelection = new java.awt.datatransfer.StringSelection (messageContentCodeArea.getText());
                    clipboard.setContents(stringSelection, null);
                    event.consume();
                }
            }
        });
```
