### ISSUE TITLE
Typing text at the end of a styled area

### ISSUE THREAD

**Issue by benedictleejh** [TomasMikula/RichTextFX#162]
When the caret is placed at the end of a styled section, any new typed text will also belong to that styled section. Sometimes, this is what you want, but not all the time. For those times where you don't want the new text to inherit the style of the styled section, how can I temporarily disable that extending of the previous style span when new text is typed?

**Comment by melkhaldi** [comment]
Why not apply a new style to caret position, then enter the new text?

**Comment by TomasMikula** [comment]
I'm sorry, somehow I missed this before. You can set the [`useInitialStyleForInsertion`](http://www.fxmisc.org/richtext/javadoc/org/fxmisc/richtext/StyledTextArea.html#useInitialStyleForInsertionProperty) property to `true` to use the default style of the text area, instead of the style immediately before the caret. To reset the behavior, just set it back to `false`.

@melkhaldi One can apply style only to a non-empty range of text, i.e. style of at least one character would have to be updated.

**Comment by benedictleejh** [comment]
Thanks @TomasMikula, that's exactly what I was looking for.
