### ISSUE TITLE
-fx-highlight-fill does not work

### ISSUE THREAD

**Issue by jmak35** [TomasMikula/RichTextFX#192]
HI Tomas,

There's an issue setting text highlights. If you run your ManualHighlighting.java application and change the "blue" class in manual-highlighting.css to apply "-fx-highlight-text-fill: blue" instead like so:
```
.blue {
    -fx-highlight-text-fill: blue;
}
```
I've even tried -fx-highlight-fill, yet you'll notice neither will have any effect on the text when you attempt to apply it. Is this normal behaviour?

Thanks.

**Comment by TomasMikula** [comment]
It is not normal behavior, but it is a known problem that `-fx-highlight-text-fill` does not work, since `Text#impl_selectionFillProperty()` doesn't work properly for `Text` inside a `TextFlow` (and it is not public API anyway).

`-fx-highlight-fill` should work on the whole text area. I don't know if it makes much sense to try to implement it for individual fragments of text. When I select text with different styles, I prefer the highlight to be one color.

**Comment by jmak35** [comment]
Thanks for the response Tomas. There's definitely a use case for highlight individual fragments of text.

If you look at the CTRL-F find mechanism within Chrome, it is exactly the kind of function that requires this sort of highlighting. And it is this functionality I'm trying to incorporate into our application using RichTextFX.

Are you saying that it's not possible at all? Or can there be a workaround to get this feature happening?

Thanks.

**Comment by TomasMikula** [comment]
I specifically meant the color of the background of _selected_ text&mdash;that's what `-fx-highlight-fill` is (althought the name might be confusing). I would rather be that one color.

You can use `-fx-background-fill` to get what you want.

**Comment by jmak35** [comment]
Oh my goodness, I didn't even know that css property existed. Thanks so much for that Tomas, that's fixed my issue.

**Comment by TomasMikula** [comment]
It only exists in RichTextFX.

**Comment by JordanMartinez** [comment]
I'm creating the CSS cheat sheet and I think renaming `highlight-fill` would be a smart move.
