### ISSUE TITLE
Expose API for programmatic PageUp/PageDown

### ISSUE THREAD

**Issue by jmak35** [TomasMikula/RichTextFX#195]
I've got some menu items set as accelerators and would like to set their actions on the CodeArea. Below are the methods I need, with **bold** indicating that there is no corresponding method within CodeArea. I would've thought that the NavigationActions class would defined this. Why are they all in the StyledTextAreaBehavior class that cannot be accessed in CodeArea?

- cut
- copy
- paste
- redo
- **home**
- **ctrl+home**
- **end**
- **ctrl_end**
- **page up**
- **page down**
- **shift+arrow**
- **shift+ctrl+arrow**

These are mostly all navigation actions. Could you please expose them in CodeArea?

Thanks.

**Comment by TomasMikula** [comment]
Hi,

some of them are available in `NavigationActions`:

- **home** - `lineStart`
- **ctrl+home** - `start`
- **end** - `lineEnd`
- **ctrl_end** - `end`
- **shift+arrow** - `nextChar`, `previousChar`
- **shift+ctrl+arrow** - `nextWord`, `previousWord`

Others cannot be implemented with the current distinction between the control and its skin, since the control does not know how the text is displayed, so the control itself does not know where to put the caret on PageUp or Shift+Up.

**Comment by JordanMartinez** [comment]
Though there's not yet a release for this yet, the skin has now been fully removed in 3f00de3c9cc1e85b3660d8f846b26aa85153eb4f.  So, you should be able to implement these on top of RichTextFX or contribute to the project by adding them directly to `StyledTextAreaBehavior`.

**Comment by JordanMartinez** [comment]
So,  is this issue only about "page up/down" being implemented now? If so, the title should be updated.

**Comment by TomasMikula** [comment]
Thanks, I updated the title. Now that there is no skin (StyledTextArea itself is the view), this can be implemented.

**Comment by TomasMikula** [comment]
Resolved by #376
