### ISSUE TITLE
CodeArea calculates wrong length on initial text insertion

### ISSUE THREAD

**Issue by fge** [TomasMikula/RichTextFX#211]
I have recently "unearthed" a project I haven't been working on for quite a few months; before I started to work on it is used the following:

* Oracle JDK 8u25;
* RichTextFX 0.6.4.

It worked fine. And now I have updated to:

* Oracle JDK 8u65;
* RichTextFX 0.6.10

And it fails to work... I have traced back to this piece of code in my project (where `display.inputText` is a `CodeArea`):

```java
    @Override
    public void loadInputBuffer(final InputBuffer buffer)
    {
        this.buffer = buffer;

        // First argument executes in a background thread; second argument executes on the JavaFX thread
        taskRunner.compute(() -> {
            final int length = buffer.length();
            System.err.printf("INITIAL: %d\n", length);
            return buffer.extract(0, length);
        }, text -> {
            display.inputText.appendText(text);
            display.inputText.moveTo(0);
            System.err.printf("AFTER INSERT: %d\n", display.inputText.getLength());
        });
    }
```

And on stderr it prints:

    INITIAL: 44380
    AFTER INSERT: 42944

I have no idea why this is happening, but it causes my highlighting process (which modifies the text in the area!) to fail.

**Comment by fge** [comment]
Note: I have since then tried to upgrade little by little. The last working version is 0.6.7.

**Comment by TomasMikula** [comment]
Hi Francis, version [0.6.8](https://github.com/TomasMikula/RichTextFX/releases/tag/v0.6.8) changed (simplified) how line terminators are treated&mdash;only `\n` line terminators are used inside all RichTextFX text areas. If your input text contained Windows line terminators (`\r\n`), these are now replaced with a single character `\n`.

**Comment by fge** [comment]
Ah.

Well, that probably explains it but that is really not a welcome "feature" for me. For that matter I may even have input files with inconsistent line terminators :/

Grappa handles newlines in whatever form they come in, and the character offsets are absolute. Is this a definite decision on the part of RichTextFX? I love its displaying abilities but this "feature" will make my code very complicated because of that very thing :/

**Comment by fge** [comment]
OK well, there may be a solution but I don't know the API very well.

From an `InputBuffer` I can obtain the line and character from an absolute position; can I use this information to obtain the absolute position from a CodeArea?

**Comment by TomasMikula** [comment]
You can:

```java
int position = codeArea.position(row, col).toOffset();
```

**Comment by TomasMikula** [comment]
Having multiple different character sequences to represent a line break is certainly silly and causes pain to developers. Up to v0.6.7, RichTextFX kept track of the original line terminators and didn't require them to be consistent throughout the file either. This is tricky, because what line terminator should be inserted on Enter? The platform specific one, or the document specific one? And what if the document is not consistent with newlines? RichTextFX anyway tried to do the best effort to preserve newlines It turned out it was futile anyway, because Java clipboard performs newline conversions automatically, so, for example, Ctrl+C immediately followed by Ctrl+V could change the newlines in the copy/pasted text. I decided that this problem, that should not exist in the first place, is not worth spending any more energy, and go with Java's convention to internally always work with `\n` only.
