### ISSUE TITLE
focus-traversable broken

### ISSUE THREAD

**Issue by TomasMikula** [TomasMikula/RichTextFX#234]
By removing inheritance from `Control`, StyledTextArea lost the ability to be focused by <kbd>Tab</kbd>-traversal.

**Comment by JordanMartinez** [comment]
I'm not sure how the code originally distinguished between a Tab-traversal and a Tab-insertion/deletion event as they both use the same input combinations (Tab and Shift+Tab). So, that's why I might be finding it difficult to understand this issue and how to re-support the feature.

One way to re-support this again is by using the internal API. However, access to that API will be removed in Java 9, so I'm guessing that's the wrong long-term approach. 

The only other way is to override the STA's Tab handlers. However, since they use the same input combinations, overriding the defaults would also remove the user's ability to insert/delete tab characters. So, either this trade-off is left up to each developer to decide or some other input combination is used to signal a Tab-traversal event.

And because its always important to ask, why should this still be supported? Is it to keep consistency with JavaFX's TextField and TextArea classes which also allow Tab-Traversal?

(And how did you use an icon for the Tab key rather than typing "Tab" itself?)

**Comment by TomasMikula** [comment]
Originally, you could only _enter_ the StyledTextArea by <kbd>Tab</kbd>, not _leave_ it, because, as you notice, the <kbd>Tab</kbd> key handler is overridden. So entering by <kbd>Tab</kbd> is all that needs to be done in this issue. Maybe all that needs to be done is set [focusTraversableProperty](http://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html#focusTraversableProperty) to `true`?

You can type <kbd>Tab</kbd> by `<kbd>Tab</kbd>`.

**Comment by JordanMartinez** [comment]
Ah... that makes more sense! You are right again about the `focusTraversableProperty`. Once set to true, I can set the focus to one of the buttons and then <kbd>Tab</kbd> into the area. Without that, it doesn't work.

Thanks! I don't think I saw that on the [markdown cheat sheet](https://guides.github.com/features/mastering-markdown/).

**Comment by TomasMikula** [comment]
Not really markdown, just [inline HTML](http://daringfireball.net/projects/markdown/syntax#html) inside markdown.
