### ISSUE TITLE
Better separation of Model from View.

### ISSUE THREAD

**Issue by TomasMikula** [TomasMikula/RichTextFX#241]
`StyledTextArea` is a `Node` and as such takes care of rendering the visual representation of a document. In other words, `StyledTextArea` is the view. A big part of the model is represented by `EditableStyledDocument`, which is independent of the view. However, some parts of the model currently leak into `StyledTextArea`; namely undo/redo, caret position and selection. As a result, for example, to test undo/redo, one needs to instantiate the view, even though undo/redo itself doesn't depend on the view.

I propose to introduce a class (`StyledTextAreaModel`) to encapsulate the model.

**Comment by JordanMartinez** [comment]
So the proposed `StyledTextAreaModel` would have an `EditableStyledDocument` and it would move ESD's plain and rich text changes EventStreams to the model itself. Then `StyledTextArea` would be passed the model itself as Constructor param (and possibly some other things), right? 

However, due to #152, and in providing the foundation for #222 to be implemented, if caret position and selection are stored in the Model, how would each View know what to display? Would the Model have a list that stores the caret positions and selection IndexRange of each StyledTextArea that displays the model, each of which is bound to its corresponding StyledTextArea property?

**Comment by TomasMikula** [comment]
`EditableStyledDocument` would stay without change. `StyledTextArea`'s plain and rich text changes would move into `StyledTextAreaModel` and `StyledTextArea` would just delegate the corresponding methods to model. Model would not be shared, each area would have its own. However, `EditableStyledDocument` could be shared by multiple models, as it is now.

**Comment by JordanMartinez** [comment]
Ah, ok that clarifies a lot.

**Comment by JordanMartinez** [comment]
See my PR (#242)
