### ISSUE TITLE
[SNAPSHOT] Regression: setting key pressed event handler results in silently discarding all key events with non-printable codes

### ISSUE THREAD

**Issue by kuc** [TomasMikula/RichTextFX#257]
```
StyleClassedTextArea textArea = new StyleClassedTextArea();
textArea.setOnKeyPressed(event -> {});
```

After this, only letters, symbols, new lines can be entered in text field. You can't use backspace, delete, arrow keys etc.

This worked correctly in last stable version `0.6.10`.

**Comment by JordanMartinez** [comment]
Oh! Ok. Yeah, that makes sense now :smile: 

If you look at [`StyledTextAreaBehavior`'s `EventHandlerTemplate` code](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextAreaBehavior.java#L57-L130), and the [javadoc in `StyledTextArea`](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/StyledTextArea.java#L79-L103), you'll see that you're supposed to override the default event handlers in a special way.

I'm not sure why that worked for `0.6.10` though as it uses the same code...

**Comment by kuc** [comment]
Ohhh, thanks! I totally missed that, because I used `StyledTextArea` as drop-in replacement for `TextArea`. I will check if that helps.

**Comment by TomasMikula** [comment]
It worked in 0.6.10 because StyledTextAreaBehavior registered the event handlers during skin instantiation, which happens when the control is first displayed, which is typically after the user registers his or her handlers. Now that we don't have skin, StyledTextArea's handlers are registered when StyledTextArea is created, and then your `setOnKeyPressed()` call overrides the handler that StyledTextArea registered. (Printable characters keep working for you because they are handled via the `onKeyTyped` handler.)

What @JordanMartinez suggests to do will fix your problem. There is also a newer version of WellBehavedFX (package [`experimental`](https://github.com/TomasMikula/WellBehavedFX/tree/master/src/main/java/org/fxmisc/wellbehaved/event/experimental)) that uses yet another way of registering handlers that does not use the `onKeyPressed`, ... properties at all. I think the "experimental" should replace the current version and be used by RichTextFX.

**Comment by kuc** [comment]
Ok, thanks! :smile:

**Comment by JordanMartinez** [comment]
@TomasMikula This is what you guys were talking about on some bug thread regarding an InputMapping API, correct?

**Comment by TomasMikula** [comment]
Yes, exactly. I developed the new experimental version of WellBehavedFX as an alternative to the proposed input mapping API that was supposed to go into JavaFX 9, because I felt strongly that the proposed design was flawed. In the end, plans to get the API into JavaFX 9 were dropped (which I think is better than having a bad API). As a result, I got back to my work and didn't really get to release the new version.

**Comment by JordanMartinez** [comment]
Ah, ok. Cool!

**Comment by TomasMikula** [comment]
For the record, the discussion is here: [JDK-8091189](https://bugs.openjdk.java.net/browse/JDK-8091189).

I then also proposed to Jonathan Giles to work out some use cases side by side, so that we can compare the proposed designs. So I wrote [this document](http://htmlpreview.github.io/?https://github.com/TomasMikula/InputMapAPI/blob/master/use-cases.html) with some use cases and asked Jonathan to fill his solutions and optionally add more use cases. He never did it and dropping the feature for 9 was announced shortly after.

**Comment by DaveJarvis** [comment]
Using:
```
compile group: 'org.fxmisc.richtext', name: 'richtextfx', version: '0.7-M2'
```

Consider the following:

```
import static javafx.scene.input.KeyCode.AT;
import static javafx.scene.input.KeyCode.ENTER;
import static org.fxmisc.wellbehaved.event.EventPattern.keyPressed;
import static org.fxmisc.wellbehaved.event.InputMap.consume;

public class Test {
  private StyleClassedTextArea editor;

  /** Convenience method. */
  public <T extends Event, U extends T> void addEventListener(
    EventPattern<? super T, ? extends U> event, Consumer<? super U> consumer ) {
    Nodes.addInputMap( getEditor(), consume( event, consumer ) );
  }

  private void init() {
    // enterPressed gets called
    addEventListener( keyPressed( ENTER ), this::enterPressed );
    // atPressed never called
    addEventListener( keyPressed( AT ), this::atPressed );
  }

  private void atPressed( KeyEvent e ) {
    System.out.println( "@ pressed" );
  }

  private void enterPressed( KeyEvent e ) {
    System.out.println( "Enter pressed" );
  }

  private synchronized StyleClassedTextArea getEditor() {
    if( this.editor == null ) {
      setEditor( createTextArea() );
    }

    return this.editor;
  }

  protected StyleClassedTextArea createTextArea() {
    return new StyleClassedTextArea( false );
  }
}
```

**Expected Results**

When the code runs, Enter presses and @ symbol presses print messages to the console.

**Actual Results**

Only Enter presses produce print messages.

Any ideas how to work around this issue?

**Comment by DaveJarvis** [comment]
```
Nodes.addInputMap( textArea, consume( keyPressed(DIGIT2, SHIFT_DOWN), e -> atPressed( e ) ) );
```

Possibly not [cross-platform](http://www.classiccmp.org/dunfield/c64/h/front.jpg)?
