### ISSUE TITLE
Line number at top of the line and not in the middle

### ISSUE THREAD

**Issue by firm1** [TomasMikula/RichTextFX#300]
Hello,

I use StyleTextArea on my app for write markdown. I have enabled line number like that (in my code) : 

```java
import org.fxmisc.richtext.LineNumberFactory;
area.setParagraphGraphicFactory(LineNumberFactory.get(area));
```

So i have a problem, line number display at middle of line. It's possible to fix it ?

Screen

![capture d ecran de 2016-04-26 08-10-24](https://cloud.githubusercontent.com/assets/6066015/14808580/b84170ee-0b86-11e6-94ce-e0dd9906be85.png)

**Comment by TomasMikula** [comment]
Hi,

a line number created by `LineNumberFactory` is a `Label`, and it is stretched to fill the whole height of the paragraph. Since it is a `Label`, you can use any [CSS properties applicable to `Label`](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html#label). To select line number labels in the scene, you can [use the `.lineno` style class](https://github.com/TomasMikula/RichTextFX/blob/cb3b5f92cb40aef216274dc0d15242e6f05a9e1b/richtextfx/src/main/java/org/fxmisc/richtext/LineNumberFactory.java#L20). Put together, this should get you the result you want:

```css
.lineno {
    -fx-alignment: top-right;
}
```

**Comment by firm1** [comment]
Thank for all. It work fine.

I think that it would be nice to document it all
