### ISSUE TITLE
StyledTextArea no longer extends Control

### ISSUE THREAD

**Issue by effad** [TomasMikula/RichTextFX#342]
StyledTextArea used to derive from javafx.scene.control.Control. In 0.7-M1 it no longer does, thus making it uncombinable with ControlsFX Validation which requires a Control to be passed.

Since StyledTextArea has all the characteristics of a Control it should derive from javafx.scene.control.Control.

**Comment by JordanMartinez** [comment]
It no longer extends `Control` because we encountered multiple issues by adhering to that architecture mainly because of the inability to access the view.

See [Tomas' comment](https://github.com/TomasMikula/RichTextFX/issues/98#issuecomment-64445259) which summarizes the problem nicely and #205 which explains another issue relating to the view. At the same time, #152 is now doable when it wasn't before.

**Comment by JordanMartinez** [comment]
Additionally, feature requests like #150 are now easier / possible to implement.

**Comment by TomasMikula** [comment]
For reasons mentioned by Jordan, extending `Control` means more trouble than benefits for us. Do you know if there is a good reason why ControlsFX Validation wouldn't work on nodes other than `Control`?

**Comment by effad** [comment]
Thanks for the hints. It is clear now that this is not a mere oversight but a planned and reasonable design decision.

As to ControlsFX Validation requiring Control: From a quick glance it looks as if it should also work on any Node and it should just be a matter of adapting a lot of code to do so.

Considering the fact that the current validation stuff from ControlsFX should be improved / replaced anyway (https://bitbucket.org/controlsfx/controlsfx/issues/372/more-flexibility-in-validationsupport) this seems to be the correct end to change.
