### ISSUE TITLE
Question: CodeArea content modified can be checked?

### ISSUE THREAD

**Issue by edubolis** [TomasMikula/RichTextFX#569]
Hi, Everyone.

I'm working on an IDE project which, of course, allows you to open and edit multiple files at the same time.
I tried to implement a "save all" menu option; it just verifies which have been modified and saves them
I thought it would be a simple operation, but I was not able to figure out how to check whether the content of the CodeArea object was modified or not.
I think I need to create a boolean property and observe some kind of event associated with the modification, I just have not figured out which event and how it works.
Is there an example of how this can be done, for me to base? 

thanks in advanced,

Eduardo Bolis

**Comment by JordanMartinez** [comment]
There's no example for this, nor is there any API to conveniently do this for you. I see two possible approaches.

The first involves storing the text at some prior moment in time and comparing it to the text at the current moment in time. If they're the same, don't save; if different, save. Obviously, this is not very efficient, and thus the second way comes to mind.

The second way would be to use `area.richChanges()` (or `area.richTextChanges()`?). Subscribe to the EventStream and store the changes made over time into a list (e.g. `changeStream.accumulate(/* args */)`). When you decide to check whether something should be saved, reduce the list: if one change in the list is later undone on by another change in the list, then one can view both changes as though they never happened (e.g. remove them from the list). If the list is empty after reducing all changes, then either no changes were done since the last save point, or any modifications that changed something were reverted by other future modifications, so that the state of the area is the same as before. If the reduction finds even one change that cannot be reverted by another, then save it.

**Comment by edubolis** [comment]
Thanks for your answer. 
It is a very complete solution (the second way) and I want to do this, but as a first step, can I will check only if the list is empty or not? It is not the ideal but it´s fast and more easy to implement, because time isn't my best friend by now...

**Comment by JordanMartinez** [comment]
That makes sense. Just do this:
````java
        codeArea.richChanges()
                // ignore changes that do nothing (i.g. computation changes)
                .filter(ch -> !ch.isIdentity())
                // only run next part if no new change is emitted in 500 ms
                .successionEnds(Duration.ofMillis(500))
                // now save the text
                .subscribe(ignore -> saveAreaContent());
````
([Taken and modified from the JavaKeywordsAsync demo](https://github.com/TomasMikula/RichTextFX/blob/99770e5fc6717a692eec6b2e3a9860662bda5e3d/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywordsAsync.java#L93-L96))

**Comment by TomasMikula** [comment]
There is also [atMarkedPosition](http://fxmisc.github.io/undo/javadoc/1.3.1/org/fxmisc/undo/UndoManager.html#atMarkedPositionProperty) property on the undo manager. Just call the [`mark()`](http://fxmisc.github.io/undo/javadoc/1.3.1/org/fxmisc/undo/UndoManager.html#mark--) method on each save. If any changes are made (or undone), `atMarkedPosition` will be `false`.

**Comment by edubolis** [comment]
Well, that is what I did:

1) I call this method just after create the CodeArea object

  _public void subscribe(CodeArea codeArea)
  {
    codeArea.plainTextChanges().subscribe(ptc -> 
    {
      modified=true;
      owner.setGraphic(UNSAVED_ICON); // a red icon to sinalize a modification
    }); 
  }_

2) when I try to save, I check _modified_ to verify the real need to, and after save, reset it to false.

If you wish, I can post the entire code, just tell me how to put it in a box and with syntax hilight the way you do.
