### ISSUE TITLE
Is it possible to add OSGI support?

### ISSUE THREAD

**Issue by PashaTurok** [TomasMikula/RichTextFX#570]
RichTextFX library is wonderful. But it is not OSGI. Of course it is possible to download the source code and add it to osgi project but then it must be done for every release. Is it possible to add OSGI support?

**Comment by JordanMartinez** [comment]
Mind submitting a PR for that? You'll still need to build RichTextFX with
Jitpack.

**Comment by PashaTurok** [comment]
@JordanMartinez I work only with maven and know how to build osgi bundles using maven. I can add parent pom and child pom both to this project and to ReactFX, if you approve the idea.

**Comment by JordanMartinez** [comment]
@PashaTurok I only have write access to RichTextFX, not ReactFX. So, while I could add it here, it wouldn't be the case for ReactFX. Even if you or I did submit a PR for OSGI on ReactFX, Tomas hasn't merged other PRs I have made months ago. You'd be better off creating your own fork, adding it there, and using that is RichTextFX's dependency instead of it's default one.

**Comment by PashaTurok** [comment]
@TomasMikula Could you say if you will allow to add POMs with OSGi support to both projects?
