### ISSUE TITLE
Inserting graphic in the text

### ISSUE THREAD

**Issue by ghost** [TomasMikula/RichTextFX#87]
Hi Tomas, 
Is there a way for me to assign a graphic to a line.
I would like to be able to add a line across the width of text area.

For example, when I concatenate multiple StyledDocs into a single text area, I would like them to be separated by lines.

Please let me know if there is a way for me to explore this.
Best,
Maher

**Comment by MewesK** [comment]
I think this feature could be used to implement code folding since the inserted node could hold the text it has to replace and could be rendered as [...]
The difficult part in that case would be to change the delete behavior of the control to not just delete the whole node if the user presses backspace.

I guess this could be something I'll look into after the paragraph style feature.

**Comment by TomasMikula** [comment]
I don't think this is a good way to implement code folding. For one, it would mess up text indices and line number.

I have another idea how to implement code folding in mind, using paragraph graphic and custom EditableStyledDocument. It will however require some preparatory refactoring first.

**Comment by JordanMartinez** [comment]
This was implemented by #356
